name: 编译mipsel版

on:
  #schedule:
    #- cron: '0 3,20 * * *'
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
  TZ: Asia/Shanghai
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      ver: ${{ steps.getversion.outputs.ver }}
      cver: ${{ steps.getversion.outputs.cver }}
    steps:
      -
        name: 检查更新
        id: getversion
        run: |
          ver=`curl https://api.github.com/repos/mullvad/udp-over-tcp/releases/latest | jq -r '.tag_name'`
          cver=`curl https://api.github.com/repos/lmq8267/tailscale/releases/latest | jq -r '.tag_name'`
          echo "ver=${ver}" >> $GITHUB_OUTPUT
          echo "cver=${cver}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.ver != needs.check.outputs.cver }}
    steps:
      -
        name: 检查代码仓库
        uses: actions/checkout@v3
      - name: Init submodules
        uses: snickerbockers/submodules-init@v4
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ./target
          key: build-cargo-registry-mipsel-unknown-linux-musl
      - name: List
        run: find ./
      - 
        name: 编译
        run: |
          mkdir -p ./musl_gcc 
          wget -c https://musl.cc/mipsel-linux-musl-cross.tgz -P ./musl_gcc/
          tar zxf ./musl_gcc/mipsel-linux-musl-cross.tgz -C ./musl_gcc/
          sudo ln -s $(pwd)/musl_gcc/mipsel-linux-musl-cross/bin/*gcc /usr/bin/
          rustup target add mipsel-unknown-linux-musl
          cat >>~/.cargo/config <<EOF
          [target.mipsel-unknown-linux-musl]
          linker = "mipsel-linux-musl-gcc"
          rustflags = ["-C", "target-feature=+crt-static"]
          EOF
          git clone https://github.com/mullvad/udp-over-tcp.git /opt/udp
          git clone https://github.com/lmq8267/cloudflared.git /opt/st
          tar -xvf /opt/st/upx-3.95-amd64_linux.tar.xz -C /opt
          chmod 777 /opt/upx-3.95-amd64_linux/upx
          chmod 777 /opt/st/strip
          mkdir -p /opt/mipsel
          cd /opt/udp
          cargo build --target=mipsel-unknown-linux-musl --release --features env_logger --features clap --bins
          cd /opt/udp/target/mipsel-unknown-linux-musl/release
          ls
           cd /opt/vnt-mipsel
          /opt/st/strip /opt/vnt-mipsel/vnt-cli
          /opt/upx-3.95-amd64_linux/upx --lzma --best vnt-cli
          echo $(md5sum vnt-cli | awk '{print $1;}') >MD5.txt
          cd /opt/vnt
          cargo clean
          cargo build --package vnt-cli --target=mipsel-unknown-linux-musl --release --features default
          mkdir -p /opt/vnt1
          cp -f /opt/vnt/target/mipsel-unknown-linux-musl/release/vnt-cli /opt/vnt1/vnt-cli_lite
          cd /opt/vnt1
          /opt/st/strip /opt/vnt1/vnt-cli_lite
          /opt/upx-3.95-amd64_linux/upx --lzma --best vnt-cli_lite
          echo $(md5sum vnt-cli_lite | awk '{print $1;}') >lite_MD5.txt
          echo "build_time=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - 
        name: 发布
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.c8 }}
          body: |
           > ### 编译时间 ：${{ env.build_time }}

           ### **各版本区别**
           
           - **vnt-cli** ：正常版 MD5.txt为其MD5检验值 
           
           - **vnt-cli_lite** ：去掉openssl的精简版 lite_MD5.txt为其MD5校验值

           如果使用加密，则集成openssl的速度更快，不加密是否集成openssl都不影响速度。

           **[官方更新说明](https://github.com/lbl8603/vnt/releases)**
          tag_name: ${{ needs.check.outputs.ver }}
          files: |
              /opt/vnt-mipsel/vnt-cli
              /opt/vnt-mipsel/MD5.txt
              /opt/vnt1/vnt-cli_lite
              /opt/vnt1/lite_MD5.txt
      - 
       name: 删除工作流
       uses: GitRML/delete-workflow-runs@main
       with:
        token: ${{ secrets.c8 }}
        retain_days: 2
        keep_minimum_runs: 0
